"""add assigned_pic to tender_watchlist

Revision ID: fbec3b43ea51
Revises: 
Create Date: 2026-05-05 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec3b43ea51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_watchlist', sa.Column('assigned_pic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_watchlist', 'assigned_pic')
    # ### end Alembic commands ###
