"""add assigned_pic to tender_watchlist

Revision ID: fbec3b43ea51
Revises: 
Create Date: 2026-05-05 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbec3b43ea51'
down_revision = None
branch_labels = None
depends_on = None


def _table_exists(table: str) -> bool:
    """Return ``True`` when ``table`` already exists on the bound DB.

    Makes the migration a clean no-op when run against a fresh DB where
    ``Base.metadata.create_all`` has not yet been invoked (e.g. first container
    boot, where Alembic runs before the FastAPI lifespan).
    """
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return table in insp.get_table_names()


def _add_column_if_absent(table: str, column: sa.Column) -> None:
    """Add ``column`` to ``table`` only if it isn't already present.

    Skips silently when ``table`` doesn't exist yet so a single ``alembic
    upgrade head`` can be run against an empty DB without failing.
    """
    if not _table_exists(table):
        return
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = {c['name'] for c in insp.get_columns(table)}
    if column.name not in existing:
        op.add_column(table, column)


def _drop_column_if_present(table: str, column_name: str) -> None:
    """Drop ``column_name`` from ``table`` only if table + column exist."""
    if not _table_exists(table):
        return
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = {c['name'] for c in insp.get_columns(table)}
    if column_name in existing:
        op.drop_column(table, column_name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _add_column_if_absent(
        'tender_watchlist',
        sa.Column('assigned_pic', sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_column_if_present('tender_watchlist', 'assigned_pic')
    # ### end Alembic commands ###
